chat-delay: 1
broadcast-delay: 6000
spawn: 0,0,0,0,0,world
announcements:
  announcement1:
    - '&r'
    - '&r'
    - '[center]&c&lCheck our discord out!'
    - '[center]&7You can get the link by doing /discord'
    - '&r'
    - '&r'
  announcement2:
    - '&r'
    - '&r'
    - '[center]&4&lExtreme/excessive camping is punishable'
    - '&r'
    - '&r'
  announcement3:
    - '&r'
    - '&r'
    - '[center]&6&lSee a hacker?'
    - '[center]&3&lDo /report [player] [reason]'
    - '&r'
    - '&r'